mixed-port: 7890
redir-port: 7892
tproxy-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: error
ipv6: false
external-controller: 0.0.0.0:9595
external-ui: /etc/mihomo/ui
secret: "flclash123"

# ⚡ Performance Boost
tcp-concurrent: true
unified-delay: false
global-client-fingerprint: chrome

profile:
  store-selected: true

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: redir-host
  nameserver:
    - 1.1.1.1
    - 8.8.8.8
    - 1.0.0.1
  proxy-server-nameserver:
    - 1.1.1.1
    - 8.8.8.8
  respect-rules: true

proxies: []

proxy-groups:
  - name: "🌀 Uzumaki-Auto"
    type: url-test
    proxies:
      - DIRECT
    url: http://www.gstatic.com/generate_204
    interval: 120
    tolerance: 20
    lazy: true

rules:
  - 'IP-CIDR,127.0.0.0/8,DIRECT,no-resolve'
  - 'IP-CIDR,192.168.0.0/16,DIRECT,no-resolve'
  - 'IP-CIDR,10.0.0.0/8,DIRECT,no-resolve'
  - 'IP-CIDR,172.16.0.0/12,DIRECT,no-resolve'
  - 'DOMAIN-SUFFIX,local,DIRECT'
  - 'DOMAIN-SUFFIX,lan,DIRECT'
  # 🌀 Gaming, UltraViewer & Microsoft Bypass
  - 'DOMAIN-KEYWORD,riotgames,DIRECT'
  - 'DOMAIN-KEYWORD,playvalorant,DIRECT'
  - 'DOMAIN-SUFFIX,pvp.net,DIRECT'
  - 'DOMAIN-KEYWORD,microsoft,DIRECT'
  - 'DOMAIN-KEYWORD,windows,DIRECT'
  - 'DOMAIN-KEYWORD,ultraviewer,DIRECT'
  - 'DOMAIN-SUFFIX,bd,DIRECT'
  - 'DOMAIN-KEYWORD,bkash,DIRECT'
  - 'DOMAIN-SUFFIX,speedtest.net,DIRECT'
  - 'DST-PORT,9595,DIRECT'
  - 'MATCH,🌀 Uzumaki-Auto'
