mixed-port: 7890
tproxy-port: 7893
allow-lan: true
bind-address: '*'
mode: rule
log-level: error
ipv6: false
external-controller: 0.0.0.0:9595
external-ui: /etc/mihomo/ui
secret: "flclash123"
tcp-concurrent: true
unified-delay: true

sniffer:
  enable: true
  sniff:
    HTTP: {ports: [80, 8080-8880], override-destination: true}
    TLS: {ports: [443, 8443], override-destination: true}
    QUIC: {ports: [443, 8443], override-destination: true}

dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.local'
    - 'time.*.com'
    - 'ntp.*.com'
    - '+.pool.ntp.org'
    - '+.msftconnecttest.com'
    - '+.msftncsi.com'
    - '+.microsoft.com'
    - '+.windowsupdate.com'
    - '+.microsoftstore.com'
    - '+.xboxlive.com'
    - '+.riotgames.com'
    - '+.pvp.net'
    - '+.playvalorant.com'
    - '+.riotcdn.net'
    - '+.si.riotgames.com'
    - '+.stun.*.*'
    - '+.stun.*.*.*'
    - 'localhost.ptlogin2.qq.com'
  default-nameserver: [1.1.1.1, 8.8.8.8]
  nameserver: [1.1.1.1, 8.8.8.8]

proxies: []
proxy-groups:
  - name: "🌀 Uzumaki-Auto"
    type: url-test
    proxies: [DIRECT]
    url: http://www.gstatic.com/generate_204
    interval: 120
rules:
  - 'IP-CIDR,192.168.0.0/16,DIRECT,no-resolve'
  - 'DOMAIN-KEYWORD,riotgames,PROXY'
  - 'DOMAIN-KEYWORD,playvalorant,PROXY'
  - 'DOMAIN-SUFFIX,pvp.net,PROXY'
  - 'DOMAIN-KEYWORD,microsoft,DIRECT'
  - 'MATCH,🌀 Uzumaki-Auto'
