table ip uzumaki {
    set bypass_ips {
        type ipv4_addr
        flags interval
        elements = { 
            0.0.0.0/8, 
            10.0.0.0/8, 
            127.0.0.0/8, 
            169.254.0.0/16, 
            172.16.0.0/12, 
            192.168.0.0/16, 
            224.0.0.0/4, 
            240.0.0.0/4,
            162.249.72.0/22,
            192.64.168.0/22,
            172.65.0.0/16,
            103.240.224.0/22,
            103.2.196.0/22,
            151.106.0.0/16
        }
    }

    chain prerouting {
        type nat hook prerouting priority dstnat - 1; policy accept;

        # 1. Local Network & Riot Games WAN Bypass
        ip daddr @bypass_ips return

        # 2. DNS Hijack to Uzumaki Local DNS (Port 1053)
        udp dport 53 counter redirect to :1053
        tcp dport 53 counter redirect to :1053

        # 3. Riot Games & Valorant Pre-Proxy Direct Port Bypass
        tcp dport { 2099, 5222, 5223, 8393-8400, 8443 } return
        udp dport { 3478-3481, 5000-5500, 7000-8000, 61500-62000 } return

        # 4. Redirect TCP Traffic to Mihomo Engine (Port 7892)
        meta l4proto tcp counter redirect to :7892
    }
}
